### ISSUE TITLE
--init + repl doesn't work

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1035]
```
bb --init /tmp/start.clj repl
```

This should load the file `/tmp/start.clj` and then start a repl.

/cc @bobisageek

**Comment by borkdude** [comment]
Another thought, while I was trying this out, I typed:

```
bb --i /tmp/start.clj repl
```

But `-i` was already taken for the `*input*` stuff (I didn't realize very early on that this was an option for clojure.main since I hadn't used this before).

Perhaps it's better to rename `--init` to `--preload-file` and also have a `--preload` for an expression, both as global opts?

**Comment by bobisageek** [comment]
I see what happened with regard to the first point - basically, I missed the parsing distinction between the global opts and the after-subcommand opts. That should be an easy fix, and I'll also write more tests to cover subcommand scenarios.

Regarding the naming - the original issue wanted to sort of swap `bb` into the `clojure` command line - I'm not really fussed either way, but I'll just throw out a suggestion to play "devil's advocate": have both `--init` and `--preload-file` as synonyms, so that people who want to do the swap from clojure to bb can, and people that want to do think of it as a file version of `BABASHKA_PRELOADS` can use `--preload-file`?

Also, were you thinking that usage of `--preload` would override/negate any value in the `BABASHKA_PRELOADS` env var, or would be loaded in addition to the env var contents?

**Comment by bobisageek** [comment]
I have a fix and tests that use subcommands (the repl one is a bit ugly because of the extra output, but it works). To save CI cycles, I won't create the PR until we finalize the naming.

One other thing that popped into my head while running tests - I know this is super-nitpicky and pedantic (that's just what my mind does), but would you prefer `--preloads-file` and `--preloads` (pluralized) in order to be consistent with `BABASHKA_PRELOADS`?
