### ISSUE TITLE
Compatibility with ring/ring-codec

### ISSUE THREAD

**Issue by FieryCod** [babashka/babashka#1091]
**Is your feature request related to a problem? Please describe.**
I would love to be able to use [ring/ring-codec](https://github.com/ring-clojure/ring-codec/blob/master/src/ring/util/codec.clj) in [holy-lambda-ring-adapter](https://github.com/FieryCod/holy-lambda-ring-adapter), but unfortunately `java.util.StringTokenizer` is not available in `babashka`.

**Describe the solution you'd like**
May I please propose a PR in which I would add `java.util.StringTokenizer` to a list of supported classes?

**Describe alternatives you've considered**
Making a fork of ring-codec without StringTokenizer.

**Comment by borkdude** [comment]
You can see an earlier commit in the history of ring-codec in which I made it compatible with babashka. It's a pity that this commit has made it incompatible again:

https://github.com/ring-clojure/ring-codec/commit/92a2d661045bed9c9b24e0ad49fff2d436d3d380#diff-e42d7d4760cc0ec1368c75ec5ec79429d64d6795c32717c6576540162ceffc9a 

/cc @bsless  

The paradox with babashka is that lower level code like this is usually slower (or incompatible) with bb than using high level constructs since there is more interpretation overhead.

Perhaps we can just maintain a fork of this library or introduce a reader conditional into the main repo, but I'm not sure if the original maintainer is OK with that.

**Comment by borkdude** [comment]
However, by adding this class, it will make things compatible again. I've tested it locally:

``` clojure
(prn (reduce (fn [m param]
               (prn param) m)
             {} (tokenized "foo&bar&baz" "&")))
```

```
"foo"
"bar"
"baz"
{}
```

I'll make a branch and let CI run it to see what the increased binary size would be.

**Comment by borkdude** [comment]
Benchmark:

``` clojure
(time
 (dotimes [_ 100000]
   (vec (tokenized "foo&bar&baz" "&"))))

(time
 (dotimes [_ 100000]
   (str/split "foo&bar&baz" #"&")))
```

```
"Elapsed time: 1954.26187 msecs"
"Elapsed time: 80.096692 msecs"
```

I'm ok with adding the class, since it doesn't take a lot of space, but it does seem to degrade performance somewhat.

**Comment by borkdude** [comment]
Merged: https://github.com/babashka/babashka/pull/1092

**Comment by FieryCod** [comment]
Thank you!

**Comment by borkdude** [comment]
Btw, there are some optimizations to be made with respect to interop. The method to invoke can be detected at analysis time rather than run time. This would speed up things considerably for this example, I think.

**Comment by borkdude** [comment]
See https://github.com/babashka/sci/issues/516 and https://github.com/babashka/sci/issues/644.
