### ISSUE TITLE
No matching method assoc found for Associative

### ISSUE THREAD

**Issue by arichiardi** [babashka/babashka#1385]
**version**
`v0.10.163`

**platform**

JVM

**problem**
The following does not work in `bb`:

```clojure
Clojure rocks, Bash reaches.

user=> (.assoc ^clojure.lang.Associative {} :foo "bar")
No matching method assoc found taking 2 args for class clojure.lang.PersistentArrayMap
```

JVM behavior

```clojure
Clojure 1.11.1
user=> (.assoc ^clojure.lang.Associative {} :foo "bar")
{:foo "bar"}
```

If this sounds good to you, I can PR this one cause this optimization is wide-spread (unfortunately) in our code base.
I might need some guidance on how to tweak the native conf though cause I have never done it before...

**Comment by arichiardi** [comment]
I do have a workaround for this with the conditionals but I'd lose the optimization, the we got from here (thanks metosin!)

https://github.com/metosin/reitit/blob/198cfda00d20093f3d7b3069e5e902835c396698/modules/reitit-core/src/reitit/impl.cljc#L144-L146

**Comment by borkdude** [comment]
This optimization doesn't make sense for bb since interop is slower than going through a pre-compiled function like `assoc`. But nonetheless we could add it.

The solution is to move this:

https://github.com/babashka/babashka/blob/7e77ab56338dd4fbbcc3b4ea462f2fe7173627f3/src/babashka/impl/classes.clj#L495

to:

https://github.com/babashka/babashka/blob/7e77ab56338dd4fbbcc3b4ea462f2fe7173627f3/src/babashka/impl/classes.clj#L139 

with the respective method

**Comment by arichiardi** [comment]
I am happy with the answer "it does not make sense" to be honest. In our code base the performance improvement is negligible.
It would be worth adding it so that we can make `reitit` closer to be supported? On the other end a conditional would also probably suffice there.
Let me know what is your preference and I'll either send a PR over or close the issue

**Comment by borkdude** [comment]
I think a conditional would be appropriate here for now. Feel free to come back if there are new insights.
