### ISSUE TITLE
Add clojure.java.javadoc

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1428]

**Comment by bobisageek** [comment]
I've been messing around with this a bit, but I ran into a small issue with `browse-url` (used by the `javadoc` function) on Windows that I'd like to get an opinion on before the PR...

The gist is that Windows' handling of arguments with special characters (in the repro case, '&') is... interesting. So, all the 'bad' behavior I'm describing here is 'on Windows' (so I'll stop mentioning that everywhere).

### Context

Running `javadoc` on a class whose package prefix isn't in `*remote-javadocs*` creates a "feeling lucky" google URL, so:
```clojure
(require '[clojure.java.javadoc :as jd])
(import (clojure.lang IFn))
(jd/javadoc IFn)
```
tries to load the URL `http://www.google.com/search?btnI=I%27m%20Feeling%20Lucky&q=allinurl:clojure/lang/IFn.html`

### Default `browse-url` behavior

this URL 'breaks' bb's current `browse-url` with the default behavior (no change to `*open-url-script*`):
```clojure
user=> (browse/browse-url "http://www.google.com/search?btnI=I%27m%20Feeling%20Lucky&q=allinurl:clojure/lang/IFn.html")
{:exit 1, :out "", :err "'q' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"}
```
and the browser loads some "google doodles" page (from the URL up to the '&'). My current branch addresses this by quoting the URL (with some other messiness that addresses ambiguity in `start`'s argument handling). This seems viable in the case of using `start` because the executable and arguments are pretty fixed.

### Using `*open-url-script*`

Where it gets a little messy is with `*open-url-script*`. The argument doesn't get quoted, so there isn't really a way for `*open-url-script*` to get a URL with an '&'. For example, with batch or shell scripts that are basically "echo the parameters", linux works nicely, windows doesn't:
```clojure
(browse/browse-url "http://www.google.com/search?btnI=I%27m%20Feeling%20Lucky&q=allinurl:clojure/lang/IFn.html")
; linux
{:exit 0, :out "http://www.google.com/search?btnI=I%27m%20Feeling%20Lucky&q=allinurl:clojure/lang/IFn.html\n", :err ""}
; windows
{:exit 1, :out "http://www.google.com/search?btnI=I%27m%20Feeling%20Lucky\r\n", :err "'q' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"}
```

It's probably prudent to note here that this `*open-url-script*` behavior is consistent with JVM Clojure (linux gets the whole URL, Windows gets the URL chopped off at the '&').

#### Options (that jump out to me)
- Leave it as-is: this would keep bb aligned with clojure JVM, especially in this java-centric part of the stdlib
- on windows, quote the URL: this has the potential of breaking existing code that uses `*open-url-script*`, but might help future consumers by making the whole URL available
  - there's a slight hiccup in this strategy, where quoting actually includes the quotes in the parameter, so a script would get `"https://..."` instead of `https://...`

I'm leaning toward leaving it as it is, and just tweaking the javadoc tests on windows to work around this, but I'm open to opinions (but I guess I don't want to stress it too much, because I'm not sure how heavily used "`*open-url-script*` on Windows" would be, so it's probably not a hole worth digging too deeply).

**Comment by borkdude** [comment]
Interesting. It might also not be worth adding `clojure.java.javadoc`. Even the author of `clojure.java.javadoc` forgot about its existence and recently rediscovered it, which is a sign that it's not used much at all. I just opened this issue after rediscovering it, but I actually have never used it. You know, I'm just going to close this and will re-open after significant pressure from the community :)
