### ISSUE TITLE
Requiring a namespace with a root binding being `set!` fails from socket repl 

### ISSUE THREAD

**Issue by jjttjj** [babashka/babashka#1456]
**version**

babashka v1.0.168

**platform**

linux / ubuntu

**problem**

Requiring a namespace with a root binding being `set!` fails from socket repl 

**repro**
```
bb socket-repl
```
Then connect.
```clojure
(require '[babashka.deps :as deps])
(deps/add-deps '{:deps {java-http-clj/java-http-clj {:mvn/version "0.4.3"}}})
(require '[java-http-clj.core :as http])
```
**expected behavior**

The root binding should be correctly `set!`

**Comment by borkdude** [comment]
Workaround for now:

```
(binding [*warn-on-reflection* *warn-on-reflection*]
  (require '[java-http-clj.core :as http]))
```

**Comment by borkdude** [comment]
This also happens with the nREPL server

**Comment by borkdude** [comment]
@axks @jjttjj You can install a dev build with to get the fix, until the next release, once the current master build finishes:

``` clojure
bash <(curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install) --dir /tmp --dev-build
```

**Comment by axks** [comment]
thank you!

**Comment by fonghou** [comment]
Hi, 

I tried dev build but `(set! *data-readers* {})` from nrepl-server client still errors _Can't set!: clojure.core/*data-readers* from non-binding thread test._

I'm trying to use it to setup reader macro [here](https://github.com/fonghou/nvim/blob/47a63ec6c493c914a68e714e65db2568b435fb38/after/ftplugin/clojure.lua#L31).  Because of above error, I have to use [workaround](https://github.com/fonghou/nvim/blob/47a63ec6c493c914a68e714e65db2568b435fb38/after/ftplugin/clojure.lua#L40), which is error prone. It'd be great if it works the same as in regular clojure.

Thanks!

**Comment by borkdude** [comment]
Thanks, I'll add `*data-readers*` too :)

**Comment by borkdude** [comment]
Added on master, once the build finishes `*data-readers*` should work as well with `--dev-build`
