### ISSUE TITLE
Disable :flaky tests on master branch in CI

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#1484]
I've added `^:flaky` metadata on some tests and I think I want to disable those in CI when on the master branch, so they won't interfere with releasing. 

One way how to do this is to remove the `:test` metadata from the vars that have flaky metadata in the test namespaces, so we don't have to do any Windows vs *Nix scripting and this will also be a lein vs deps.edn compatible solution.

_Originally posted by @borkdude in https://github.com/babashka/babashka/issues/1483#issuecomment-1416862032_

**Comment by bobisageek** [comment]
an idea that I was tinkering with...

Given:
- lein test selectors can take parameters
- cognitect.test-runner takes an `:excludes` parameter for test var metadata
- the `:flaky` test metadata accompanies the existing `:skip-windows` and `:windows-only` markers

Proposal: implement what is essentially the `:excludes` logic as a leiningen test selector
- minimal new code/custom metadata manipulation
- re-uses the existing test metadata
- compatible with lein and cognitect.test-runner (although not identical usage): lein would look something like `lein test :excludes flaky windows-only` and test-runner would look like `clj -X:test :excludes '[:flaky :windows-only]'`
- it would be slightly different for windows vs *nix; but only a change to the keywords to exclude

**Comment by borkdude** [comment]
But I'd like to do this only on the main branch, which is the more complicated part. And I'd also like to add more .bat-specific scripting if I can avoid it :)

**Comment by bobisageek** [comment]
Clarification question: according to AppVeyor docs, `APPVEYOR_REPO_BRANCH` is the base branch on PRs, meaning it would typically be master for PRs. I'm assuming that, given the motivation of release interference, that the disabling should not happen on PRs; is that correct?

The reason I ask is because (if I'm putting the pieces together correctly), AppVeyor can do branch-specific config, but distinguishing between a build of master and a PR to master is a bit messier. Based on https://www.appveyor.com/docs/branches/#sharing-common-configuration-between-branches, we could do something like:
```
for:
- branches:
   only: master
  test_script:
  - cmd: ... test.bat :excludes skip-windows flaky

- test_script
  - cmd: ... test.bat :excludes skip-windows
```
 
This should make the default test_script (which should run after build_script) run all the "windows-safe" tests, but when on master, override the test_script to exclude the flaky tests. The only batch scripting necessary in this case would be to change the hard-coded `:windows` in `test.bat` to take arguments like the `test` script does. However, presumably since the branch var would be master on PRs to master, the master branch config would also catch PRs.

This could be enhanced with branching based on the PR vars, sort of like the clone_script, if the desire is that the flaky tests should not run on master builds, but should run on PRs to master. That's definitely additional scripting, but we could do it with powershell instead of batch (maybe the lesser of two evils??).

Based on the answer, I can put together a PR that we could try out... to avoid interfering with master, I could base it off another branch to test things out if you'd like, and we could do a PR with that as the base branch, then build that base branch, and verify that the corresponding test selectors get used for each.

**Comment by borkdude** [comment]
The main goal is not to interfere with a release process. I've had a couple of times that I didn't get binary artifact because some http test was flaky. I'm using this for detecting if it's the main branch in `script/babashka/release_artifact.clj`:

```
(defn current-branch []
  (or (System/getenv "APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH")
      (System/getenv "APPVEYOR_REPO_BRANCH")
      (System/getenv "CIRCLE_BRANCH")
      (System/getenv "GITHUB_REF_NAME")
      (System/getenv "CIRRUS_BRANCH")
      (-> (sh "git" "rev-parse" "--abbrev-ref" "HEAD")
          :out
          str/trim)))
```

So far that has worked well.

Your idea sounds good.

**Comment by borkdude** [comment]
Fixed by @bobisageek in https://github.com/babashka/babashka/commit/42fd5d851f8c29a39826e4b57c1b9da53608cdc3
