### ISSUE TITLE
Mixed source and dest file using uberscripts blanks files

### ISSUE THREAD

**Issue by anderspersson** [babashka/babashka#1489]
I know did not use the tool correct, but feel is dangerus it wipes a sourcefile!

**version**
babashka v1.1.173

**platform**
Windows 11

**problem**
Tested the Unberscript and mixed source and dest file witch did blank my sourcefile. 
, mabe should give warning that a file with data exits ?

```
Directory: C:\test\bb_test

Filename: 
-a----        2023-02-09     14:32             70 source.clj

bb uberscript .\source.clj

Result:

-a----        2023-02-09     15:11              0 source.clj

```

**Comment by borkdude** [comment]
Yes, I think you're right

**Comment by bobisageek** [comment]
Just a backward-compatibility question - would the plan be for the warning to actually prevent the overwrite, or just like a notice that "[filename] is about to be overwritten"? I ask because people that might be rebuilding an uberscript when they make changes could be surprised by a change in behavior (presumably having to delete or empty the target file before running their uberscript build).

**Comment by borkdude** [comment]
@bobisageek I think we should not overwrite source files, or maybe any file that doesn't end with `.jar`. Overwriting a previous uberjar is fine, I think.
