### ISSUE TITLE
Add Java stuffs to Dockerfile

### ISSUE THREAD

**Issue by ccfontes** [babashka/babashka#1537]
**Is your feature request related to a problem? Please describe.**
Using a `babashka/babashka` docker image, I want to load external libraries using `babashka.deps/deps`, but I get this error when I try to do this:
```
(deps/add-deps '{:deps {org.babashka/spec.alpha {:git/url "https://github.com/babashka/spec.alpha"
   ^--- Couldn't find 'java'. Please set JAVA_HOME.
                                                 :git/sha "951b49b8c173244e66443b8188e3ff928a0a71e7"}}})
```

**Describe the solution you'd like**
I would like that the Java stuffs are also included in the `babashka/babashka` docker images, so that I don't see the error above.

**Additional context**
No Java stuffs: https://github.com/babashka/babashka/blob/master/Dockerfile

**Comment by borkdude** [comment]
@ccfontes The babashka/babashka docker image only contains the minimal bits to run babashka. If you need Java, it's probably better to start with a Java image and then install babashka and build your own image.

Note that you longer need babashka/spec.alpha to use clojure.spec in babashka, it's built in since a couple of versions ago.
