### ISSUE TITLE
Asahi Linux - Native ARM Linux on Apple M1/M2/M3

### ISSUE THREAD

**Issue by sitepodmatt** [babashka/babashka#1600]
Currently Babashka does not work on Asahi Linux Fedora, a spin of Fedora targetted for Apple new silicion hardware (M1/M2/M3) etc..  Asahi Linux has the main driver of native Linux support on Apple hardware, with many changes already upstreamed to the kernel, it's popularity will (imo) quickly gain pace to significant number (I expect at least 2% within 2 years) 

 Any invocation of bb yields:

```
[matt@fedora ~]$ bb
Fatal error: Failed to create the main Isolate. (code 9)
[matt@fedora ~]$ 
```

Current guess is that this is compiled with 4K pages, or perhaps this is underlying restriction with GraalVM, where as I understand sane ARM binaries should support all page sizes. Here's a comment from the developer of Asahi Linux himself:

![image](https://github.com/babashka/babashka/assets/1687145/feb4251a-34ab-4444-8742-607c7e0abf45)

Is it possible to get a build with 64K page size to test? Or enable universal page size support somehow? GraalVM flag?

**Comment by borkdude** [comment]
This doesn't ring a bell. Have you tried compiling babashka on Asahi linux itself from source?
If that also doesn't work, what I would do is the following:

Make an Hello World GraalVM binary in Java. Compile it on Asahi (or other aarch64 linux) and make an issue with GraalVM about it. Also link the issue here.

**Comment by borkdude** [comment]
From the GraalVM Slack:

Peter Zhelezniakov
  [1 minute ago](https://graalvm.slack.com/archives/CN9KSFB40/p1691749470639389?thread_ts=1691748589.864449&cid=CN9KSFB40)
IIRC binaries built on a system with 4K pages cannot run on systems with 16K pages
Peter Zhelezniakov
  [< 1 minute ago](https://graalvm.slack.com/archives/CN9KSFB40/p1691749526490609?thread_ts=1691748589.864449&cid=CN9KSFB40)
But that can probably be fixed using -H:PageSize=

**Comment by borkdude** [comment]
More news: setting `-H:PageSize=16K` might help since it will work on 4K page size systems too (since 16 is a multiple of 4).

**Comment by lewurm** [comment]
If you running `native-image` directly on Asahi it should work as it will pick up the right pagesize.  I did a couple of GraalVM smoke tests when when the Asahi installer was released a couple months ago, and that worked fine.

Alas during `native-image` build-time we assume the pagesize to be constant (= the value set via `-H:PageSize=`) and thus the generated code only works with that pagesize (or smaller).  Unlikely that we'll fix that anytime soon, especially because the easy workaround here is to use `-H:PageSize=16K`.

**Comment by lewurm** [comment]
FWIW, as marcan suggested, the better choice for shipping is `-H:PageSize=64K` on linux-aarch64. Should be future proofed then 😉

**Comment by sitepodmatt** [comment]
Managed to get to compile and run with 

```
diff --git a/script/compile b/script/compile
index 964a2b06..fcc8e47d 100755
--- a/script/compile
+++ b/script/compile
@@ -39,6 +39,7 @@ args=("-jar" "$BABASHKA_JAR"
       # "-H:DashboardDump=reports/dump"
       # "-H:+DashboardPretty"
       # "-H:+DashboardJson"
+      "-H:PageSize=64K"
       "-H:ReportAnalysisForbiddenType=java.awt.Toolkit:InHeap,Allocated"
       "--verbose"
       "--no-fallback"
```

Would make a PR but I guess we need this flag optional based on arch type?

**Comment by borkdude** [comment]
@sitepodmatt I can make a branch so you can test the binary on Asahi. If it works, then we'll keep the flag for linux aarch64.

**Comment by sitepodmatt** [comment]
@borkdude sounds good

**Comment by borkdude** [comment]
@sitepodmatt Here's the link to the binary: https://output.circle-artifacts.com/output/job/046077be-445a-4499-943d-40641c55e411/artifacts/0/release/babashka-1.3.183-SNAPSHOT-linux-aarch64-static.tar.gz

Can you let me know if it works on Asahi?

**Comment by sitepodmatt** [comment]
Works

```
[matt@fedora ~]$ ./bb
Babashka v1.3.183-SNAPSHOT REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.

user=> 
```
