### ISSUE TITLE
Document -Xmx flag

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#358]
bb accepts the following flags:

```
-Xmx128m -XX:+PrintGC -XX:+PrintGCTimeStamps -XX:+VerboseGC
```

**Comment by bobisageek** [comment]
It looks like there might be some additional `-XX` flags that are technically available (visible via `bb -XX:PrintFlags=`), although probably not as commonly used (but something like +GCPrintSummary might be nice in some cases). One nice thing about PrintFlags is that it provides help text for all the available `XX` flags (including the listed ones).

I was thinking of adding the initially listed flags to the "Global Opts" section (felt like the most appropriate place), but with the `XX` flags, the optimal approach maybe gets a bit messier: 
- include just those flags and disregard the others? 
- reference the PrintFlags flag (which gives fuller info, but kind of means there's a second help screen)? 
- document just those flags in help, and mention PrintFlags in the book (or somewhere else that's appropriate)?

**Comment by borkdude** [comment]
@bobisageek Good point. I think we could just document `-XX:PrintFlags=` in the help of babashka itself to see the "expert" options.

**Comment by bobisageek** [comment]
@borkdude Does PR #908 justify closing this one?

My aim has been to help in closing some of the doc issues (the 'low hanging fruit') so that you can think more about the trickier/hammock issues. If there's a strategy that you feel might be more helpful (look at the newer issues first or whatever), I'm happy to do that - just looking to help out.

**Comment by borkdude** [comment]
Yep, that certainly helps, thank you!
