### ISSUE TITLE
babashka.hiccup / babashka.html

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#646]
Namespace for generating hiccup.

Or should we have babashka.html where hiccup is just one of the functions? We could add more useful html-related stuff there.

**Comment by cadiv** [comment]
This will be great for me, I recently started needing alot of html parsing and selecting and have been looking for ways to do it with clojure, preferably babashka.

Specifically I would love some util function to select html elements comfortably (css selector/xpath, but more clojure styled), 
Sadly most hiccup projects I found are unmaintained, but this is closest in spirit to something I would like to have:
https://github.com/cjohansen/hiccup-find

For this reason I think it's better to have babashka.html rather than babshka.hiccup, which would also allow for these utilities to be in it too.

**Comment by borkdude** [comment]
@cadiv Also check out https://github.com/retrogradeorbit/bootleg which you can use as a pod from babashka.

**Comment by borkdude** [comment]
hiccup.core and hiccup2.core are now included in babashka 0.2.8
