### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by plasmoduck** [babashka/babashka#721]
Please make compatible with FreeBSD. Perhaps a patch or instructions how to compile or a binary?

Thanks

**Comment by borkdude** [comment]
What should be done to make it compatible with FreeBSD?

**Comment by borkdude** [comment]
Compile instructions can be found here: https://github.com/borkdude/babashka/blob/master/doc/build.md

**Comment by plasmoduck** [comment]
Thanks for that. Unfortunatly I got this error whilst doing script/uberjar

Retrieving hiccup/hiccup/2.0.0-alpha2/hiccup-2.0.0-alpha2.jar from clojars
Syntax error (FileNotFoundException) compiling at (babashka/impl/xml.clj:1:1).
Could not locate sci/impl/namespaces__init.class, sci/impl/namespaces.clj or sci/impl/namespaces.cljc on classpath.

Full report at:
/tmp/clojure-6442883182706833057.edn
Error encountered performing task 'do' with profile(s): 'base,system,user,provided,dev,xml,yaml,core-async,csv,transit,httpkit-client,httpkit-server,core-match,hiccup,test-check,reflection'
Suppressed exit

and script/compile
script/compile: line 7: GRAALVM_HOME: unbound variable

**Comment by borkdude** [comment]
@plasmoduck Take a look at the prerequisites. You should set GRAALVM_HOME to your GraalVM install.

**Comment by borkdude** [comment]
Reply from the GraalVM team:

Christian Wimmer on the GraalVM slack:

Since BSD is not a platform where Oracle supports Java on as far as I know, it can also not be a platform where Oracle supports GraalVM on.
But overall BSD is very similar to Linux. So when you build the JVMCI-JDK 11 (with all the proper JDK native libraries for static linking) and GraalVM CE yourself on BSD, it could just work or be not too much work to get running.
We certainly will accept patches if someone works on it.

**Comment by plasmoduck** [comment]
thanks for the reply. I ended up deciding not to use it.

**Comment by dbohdan** [comment]
If you found this issue because you are looking for something like Babashka for \*BSD, consider **[nbb](https://github.com/babashka/nbb)** and **[Joker](https://github.com/candid82/joker)**.

Some points:
* Joker is written in Go and compiles to a single binary, like Babashka. Nbb requires Node.js 14 or later, which is available for DragonFly/Free/Net/OpenBSD. Nbb is easy to run with `npx nbb`.
* A least simple scripts seem to work without issue in Joker on NetBSD and OpenBSD. Nbb runs [gallery.cljs](https://gist.github.com/borkdude/05c4f4ce81a988f90917dc295d8f306e) with Node.js 18 on OpenBSD. 
* Joker is significantly less compatible with regular Clojure than SCI, the interpreter that powers Babashka and nbb.
* On my Linux machine, nbb runs `(time (dotimes [i 1000000] (str "a" i "b")))` two times slower than Babashka; Joker, nine times.

**Comment by m2608** [comment]
It seems that statically linked linux version works well with ubuntu chroot installed using [this script](https://github.com/mrclksr/linux-browser-installer). 
Although I had some problems with default CentOS 7.9.2009 linux compatibility layer (specifically, when using babashka.process).

**Comment by lispyclouds** [comment]
bb is now available on FreeBSD: https://github.com/babashka/babashka#freebsd
Please do test it out and let us know of any issues!

**Comment by dbohdan** [comment]
Works for me!

```none
dbohdan@freebsd ~> bb --version
babashka v1.12.218
dbohdan@freebsd ~> bb -e '(-> (babashka.process/pipeline (babashka.process/pb "uname -a") (babashka.process/pb "nl")) last :out slurp)'
"     1\tLinux freebsd.home 5.15.0 FreeBSD 15.1-STABLE stable/15-n283666-52462498b132 GENERIC x86_64 x86_64 x86_64 GNU/Linux\n"
```
