### ISSUE TITLE
Allow to specify custom cache, lookup directories for babashka pods

### ISSUE THREAD

**Issue by FieryCod** [babashka/babashka#801]
**Is your feature request related to a problem? Please describe.**
I've created the following babashka runtime [layer](https://github.com/FieryCod/holy-lambda/tree/master/modules/holy-lambda-babashka-layer) for AWS Lambda. My approach to this problem is to bundle all common dependencies in the layer so that the user does not have to waste resources on uploading these on the new lambda version.

[Bundled](https://github.com/FieryCod/holy-lambda/blob/master/modules/holy-lambda-babashka-layer/Dockerfile#L25) dependencies:
- clojure
- holy-lambda-babashka-runtime
- bb 
- babashka-aws-pod

The layer is a .zip with dependencies specified above which is extracted upon the first lambda invocation in path `/var/opt`. Upon invocation, lambda extracts user deployed lambda artifact as well.

**User lambda artifact is a .zip with:**
- BABASHKA_ENTRYPOINT 
- output.jar (sources of application) 
- native-deps/* - various native tools and babashka pods (ex /native-deps/.babashka/pods/repository/org.babashka/babashka-sql-pods/v0.0.5/*

User lambda artifact is extracted in `/var/task` therefore babashka runtime re-downloads extra pods (not bundled in runtime), because [babashka-resolver](https://github.com/babashka/pods/blob/82aa3627106181a0ad58c289cd45129603e4fa24/src/babashka/pods/impl/resolver.clj#L120) does not allow to specify additional paths in which pods could be stored.

**Describe the solution you'd like**
I would like babashka resolver to allow specifying alternative cache lookup via an environment variable.

BABASHKA_PODS_CACHE_EXTRA_DIR="/var/task/native-deps/.babashka"

**Describe alternatives you've considered**
Force users to bundle pods in layers. (Super not user friendly)

**Comment by borkdude** [comment]
I want to avoid adding extra complexity if it's not necessary. So only if there is absolutely no other way and if this feature is more generally useful than one specific scenario, I will consider adding this. Adding a new feature is easy, but maintaining it in the prolonged future is less easy. Adding multiple possible pod paths brings questions like: where should we download new pods if they aren't yet on the system, etc.

First let's explore some other options.

In the lambda layer docs I read:

> While your function is running, it can access the content of the layer in the /opt directory. Layers are applied in the order that's specified, merging any folders with the same name. If the same file appears in multiple layers, the version in the last applied layer is used.

If this is true, why do you have the above problem?

- Can't your force both zips to be extracted to /var/opt instead of /var/task?
- Upon first execution, you could merge `/var/opt/.babashka` with `/var/task/.babashka` 
- etc.

**Comment by FieryCod** [comment]
@borkdude Thank you very much for your response. After much consideration, I've concluded that `pods` should not be bundled into a runtime itself. Instead `pods` should be packed as a separate layer, so that those will end up in the `/opt/.babashka` directory to which runtime will point to. As you said the user may provide as many layers with `pods` as one wants and still all of the layers will be merged together. 

I think that this is exactly what I wanted, therefore no changes are required on `babashka` side. Thanks again for your insights.
