### ISSUE TITLE
Support exec call

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#858]
This replaces the current process with another one.

Demo:

```
./bb -e '(do (prn (org.graalvm.nativeimage.ProcessProperties/getProcessID)) (org.graalvm.nativeimage.ProcessProperties/exec (fs/path "/bin/bash") (into-array String [""])))'
```

Concerns:

- exec may compose badly with other parts of babashka, like, you can't set an environment  (set-env has problems of its own: it doesn't compose with System/getenv since the environment in the JVM is cached on first use)

**Comment by davclark** [comment]
I'd love to see docs on how to set environment in the calling shell (if that's possible), or set environment within a shell.

For example, right now I'd like to convert this to a babashka task, but it involves `eval`ing the textual output of some `export VAR=value` commands:

```
eval $(minikube -p minikube docker-env)  # The quoted command outputs a bunch of exports
docker build -t local/image:tag .
```

Ultimately it's probably cleaner to use a more clojure-native approach to k8s, but I this general pattern comes up enough that it would help me get tasks "quick and dirty" into my bb.edn.

**Comment by borkdude** [comment]
@davclark Hi! I suppose `eval` is a bash thing. You can just execute bash with `(shell "bash -c ...")`. 
Environment variables can be set in shell using `(shell {:extra-env {"VAR" "value"}} "command")`. You can ask questions all you like at the https://github.com/babashka/babashka/discussions forum :).

**Comment by borkdude** [comment]
I will close this until we really need it.

**Comment by borkdude** [comment]
> you can't set an environment

There now seems a way to set the environment: https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/ProcessProperties.html#exec-java.nio.file.Path-java.lang.String:A-java.util.Map-

**Comment by jlb0170** [comment]
I'd definitely like to use babashka with a "native" exec semantic - the java "exec" fork/exec model means that you can't use babashka to write a truly clean "process starter" - you briefly double the memory footprint of the child process even if the child is going to be super tiny, and you wire the parent process to the child in a way that is unnecessary when that's what you are trying to build, which is, to my mind, a core use case of babashka - it's super fast to start up, so making a reasonably complex process starter is a natural fit for babashka, but this is a minor problem with actually doing so.
a) doubles memory footprint before new process is fully realized
b) requires handling in babashka code unnecessarily
c) leaves a pid/ps entry in the process table which shows up in greps and other tools rather than just dropping out after the kick off is complete

it did seem there was at least one other person in the clojurians babashka forum that chimed in seeing roughly the same need as well (Gunnar?) - hopefully they will drop by, but I thought I'd mention it as they might not make it across the feedback forum switch.

**Comment by borkdude** [comment]
@jlb0170 OK, since there are now at least a few people who'd like to see this, I think we can include it in babashka.process.

**Comment by borkdude** [comment]
Already implemented
