### ISSUE TITLE
formatter-out support for clojure.pprint

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#922]
The fork of data.json here: https://github.com/babashka/data.json runs with babashka's `formatter-out` branch.
Clojure.data.json uses `formatter-out` for pprint-ing JSON.

But using `formatter-out` in babashka/SCI yields mangled output, why?

``` clojure
user=> (babashka.main/main "-e" "(require '[clojure.pprint :as pprint])  (def print-array (pprint/formatter-out \"~<[~;~@{~w~^, ~:_~}~;]~:>\")) (pprint/with-pprint-dispatch #(if (seqable? %) (print-array %) (print %)) (with-out-str (pprint/pprint [1 2 3])))")
"[1,23 , ]\n"
```

Equivalent to executing the following file:
``` clojure
(require '[clojure.pprint :as pprint])

(def print-array (pprint/formatter-out "~<[~;~@{~w~^, ~:_~}~;]~:>"))

(pprint/with-pprint-dispatch
  #(if (seqable? %)
     (print-array %)
     (print %))
  (pprint/pprint [1 2 3]))
```

**Comment by bobisageek** [comment]
In case it helps, it seems like there might be a few slightly different behaviors here... I experimented with some longer seqs and different separator characters to look for patterns:

It seems like a general pattern is that we get the opening bracket, then the first item in the seq, then the separator*, then the rest of the seq, then all the remaining separators.

All these examples are pprinting `[1 2 3 4]`, with only the separator (between `~^` and `~:`) changing:

", " (same as original example):
`[1,234 , , ]` - some character(s) other than a space followed by a space seems to just get the separator up to the space after the first element

"<>"
`[1<>234<><>]` - separators that don't end in a space seem to get the whole separator after the first element

" ,"
`[1 ,234 , ,]` - a separator that starts with a space seems to follow the same pattern as arbitrary characters

" "
`[1234   ]` - one or more spaces as a separator seems to push all the separators after all the elements (similar behavior comes from using two or three spaces as a separator)

**Comment by bobisageek** [comment]
This is sort of a stab in the dark, so feel free to just ignore it if it doesn't make sense... any possibility that pprint/write-option-table, used in new-write, referring to "proper" clojure's `*print-pprint-dispatch*` and `*print-right-margin*` vars instead of the sci ones is somehow involved here? I'm playing around a little bit trying to determine how to test that possibility.

**Comment by borkdude** [comment]
You removed a comment, but I had read it in the mail and I think you could be on to something: it must be something similar to this.

**Comment by bobisageek** [comment]
After I re-read the pprint namespace, I saw that I had missed the alter-var-root on write-option-table, which made me think that I was probably incorrect (that's why I deleted the comment). 

Just to feel more confident with eliminating possibilities, I compiled a standalone native image of the repro in Clojure, and that printed the 'expected output', which, to me, makes it that more likely that it's something in SCI or the pprint namespace setup.

Thinking about it, it doesn't seem like `*print-pprint-dispatch*` could be totally pointed at the wrong place, because tweaking the arg to `with-pprint-dispatch` does change what prints, and if that value weren't being honored, then presumably we'd see the same output every time. Based on the output, it feels like maybe there's a write ordering or stream flushing difference or something. I'm kind of writing these things out hoping to knock some ideas loose in my head. :)

**Comment by borkdude** [comment]
Discovered another issue: `cl-format` doesn't re-bind `*out*` to SCI's out:

```
(def x (with-out-str (pprint/cl-format true "~<[~;~@{~w~^, ~:_~}~;]~:>" [1 2 3])))
(prn x (count x))
``` 
That's an easy one to fix + write a test for.

**Comment by borkdude** [comment]
Another repro that shows it's not necessarily related to `formatter-out`:

```
(require '[clojure.pprint :as pprint])

(pprint/with-pprint-dispatch
  #(if (seqable? %)
     (pprint/cl-format true "~<[~;~@{~w~^, ~:_~}~;]~:>" %)
     (print %))
  (pprint/pprint [1 2 3]))
```

**Comment by bobisageek** [comment]
so, that gave me an idea...

If we throw the other print into a `formatter-out` call, it 'works'.

```clojure
(require '[clojure.pprint :as pprint])

(def print-array-blob (pprint/formatter-out "~<[~;~@{~w~^, ~:_~}~;]~:>"))
(def print-a-thing (pprint/formatter-out "~A"))

(pprint/with-pprint-dispatch
  #(if (seqable? %)
     (print-array-blob %)
     (print-a-thing %))
  (pprint/pprint [1 2 3]))
```
prints `[1, 2, 3]` for me on the current formatter-out branch

So I think the `*out*` binding thing might be very much in play here

**Comment by borkdude** [comment]
Nice!

**Comment by borkdude** [comment]
I think the issue might be that SCI's `print` re-binds `*out*` to `sci/out`.
E.g. when I add Clojure's `print` as `pprint/print` in the namespace options, without this re-binding, then it also works. So I think the issue is that within the cl-format logic `*out*` is bound to some other stream, but we re-bind it to the vanilla out stream in `print`. 🤔

**Comment by borkdude** [comment]
Correction: the issue is that `print` inside bb writes to `sci/out`, not to `*out*`, but `sci/out` is probably not bound to the correct value of `*out*` since the cl-format logic binds `*out*` and not `sci/out` to some wrapped stream.

**Comment by bobisageek** [comment]
I don't have any real experience with the impl namespaces, but 'shadowing' `execute-format` with binding `*out*` to `@sci/out` and then calling pprint and copying `cl-format` but changing the call to the 'shadow' `execute-format` seems to work for cl-format, but I'm having some trouble with `formatter-out`, because I'm not sure about how to reference the shadowed `execute-format` from the macro. 

I'm also guessing you're probably already further ahead than I am, and I'm not really sure if blindly binding `*out*` actually makes sense on the grander scale.

**Comment by borkdude** [comment]
> I'm not sure about how to reference the shadowed execute-format from the macro.

The shadowed execute-format is automatically used because the macro is expanded in SCI and the vars it expands into are resolved from the SCI options.

**Comment by borkdude** [comment]
@bobisageek I think I got it now:

The solution is as follows:

```
(defn execute-format
  "We need to bind sci/out to *out* so all calls to clojure.core/print are directed
  to the writer bound to *out* by the cl-format logic."
  [& args]
  (sci/binding [sci/out *out*]
    (apply #'pprint/execute-format args)))
``` 
and then add this to the SCI namespace config. This will make sci programs that use `execute-format` from the macro expansion bind` sci/out` (to which `print` writes) bind to `*out*`, which is some stream that cl-format binds.

At least, it seems to work now and I hope this is a sufficient workaround :).

**Comment by borkdude** [comment]
I added some unit tests, but some extra testing wouldn't hurt. Thanks for helping out! In case you think you didn't help me solve the issue, but you did and I appreciate it.

**Comment by borkdude** [comment]
Confirming that bb master now also works properly with the JSON pretty printing in clojure.data.json (from source):

```
$ bb -cp src/main/clojure -e "(require '[clojure.data.json :as json]) (json/pprint (json/read-str (json/write-str (repeat 10 {:a 1}))))"
[{"a":1}, {"a":1}, {"a":1}, {"a":1}, {"a":1}, {"a":1}, {"a":1},
 {"a":1}, {"a":1}, {"a":1}]
```
