### ISSUE TITLE
Fix Windows native test when passing :env in clojure

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka#936]
https://github.com/babashka/babashka/blob/24d1de51a018fc0f3576febe6ae0eee76f6619d4/test/babashka/deps_test.clj#L83

/cc @bobisageek

**Comment by bobisageek** [comment]
I think that at least a contributing factor here might be `process` handling backslashes in a somewhat awkward way.

In order to understand it better, I tried to peel away all the abstractions and dependencies, and I've got it down to a _relatively_ simple repro, based on the test, that can be run in bb:

```clj
(require '[babashka.process :as p])
(require '[babashka.fs :as fs])
(require '[clojure.java.shell :as shell])

(let [libs-dir (fs/file (fs/create-temp-dir) ".gitlibs")
      template (pr-str '(do (babashka.deps/clojure 
                             ["-Sforce" "-Spath" "-Sdeps" "{:deps {babashka/process {:git/url \"https://github.com/babashka/process\" :sha \"4c6699d06b49773d3e5c5b4c11d3334fb78cc996\"}}}"]
                             {:out     :string
                              :env-key {"PATH"    (System/getenv "PATH")
                                        "GITLIBS" :gitlibs}}) nil))
      a (-> template (str/replace ":gitlibs" (pr-str (str libs-dir)))
            (str/replace ":env-key" ":env"))
      _ (println a)]
  (println "===Process run===")
  (println @(p/process ["bb" a] {:out :string :err :string}))
  (println "===Sh run===")
  (println (shell/sh "bb" (pr-str a))))
```

On Windows, the Process run fails with that same `Unsupported escape character: \h` message. But with the repro, I can also see the `:cmd` from the process object:
`:cmd [bb (do (babashka.deps/clojure [\"-Sforce\" \"-Spath\" \"-Sdeps\" \"{:deps {babashka/process {:git/url \\"https://github.com/babashka/process\\" :sha \\"4c6699d06b49773d3e5c5b4c11d3334fb78cc996\\"}}}\"] {:out :string, :env {\"PATH\" (System/getenv \"PATH\")...`

If you look at the URL and sha in the :deps map, it looks like the backslashes are wrong... there should be three backslashes before the double-quotes, correct?

I'm going to keep playing and try to get down to a really small repro, but maybe this will provide some ideas on which to start building.

Side note: when I run this same script on Linux (WSL), the process run works as expected, but the `clojure.java.shell/sh` run needs to be passed just `a` instead of `(pr-str a)`.

**Comment by bobisageek** [comment]
A trivial repro:

```clj
(require '[babashka.process :as p])

(println @(p/process ["bb" "(println \"a\\\"b\\\"c\")"] {:out :string :err :string}))
```

This fails on Windows with the message `Unsupported escape character: \c.` and a `:cmd` of `[bb (println \"a\\"b\\"c\")]`, and succeeds on Linux (WSL) with the expected output of `a"b"c` and a `:cmd` of `[bb (println "a\"b\"c")]`.

**Comment by bobisageek** [comment]
This is quote possibly me speaking out of school here, but I went into the `babashka.process` namespace and started playing around...

```clj
(def bb-pb (build ["bb" (pr-str '(println "a\"b\"c"))]))
=> #'babashka.process/bb-pb
(def pb (java.lang.ProcessBuilder. ["bb" (pr-str '(println "a\"b\"c"))]))
=> #'babashka.process/pb

(println (.command bb-pb))
[bb (println \"a\\"b\\"c\")]

(println (.command pb))
[bb (println "a\"b\"c")]
```

So, if my assumption is correct that calling `b.process/build` with a list and constructing a ProcessBuilder with that same list should result in equivalent ProcessBuilder instances, then that seems like it might be the root cause, and _possibly_ all that needs to change is for `:escape` in `*defaults*` to be changed to identity for any platform. But I realize I'm jumping to conclusions based on assumptions, so definitely tell me if I've got things wrong there.

**Comment by borkdude** [comment]
The reason `:escape` is like this, is because passing EDN of JSON with strings in them as command line arguments doesn't work by default in Windows.

**Comment by borkdude** [comment]
Here is a repro of that:

```
user=> (def pb (java.lang.ProcessBuilder. ["deps" "-Spath" "-Sdeps" "{:deps {medley/medley {:mvn/version \"1.3.1\"}}}"]))
#'user/pb
user=> (def proc (.start pb))
#'user/proc
user=> (slurp (.getErrorStream proc))
""
user=> (slurp (.getInputStream proc))
"Error while parsing option \"--config-data {:deps {medley/medley {:mvn/version 1.3.1}}}\": java.lang.NumberFormatException: Invalid number: 1.3.1\r\n"
``` 

Perhaps the "fix"  in babashka.process isn't appropriate but I've used this workaround in almost all of my projects for Windows + ProcessBuilder.

**Comment by borkdude** [comment]
@puredanger I expect the above example also not to work with tools.build process btw (https://github.com/babashka/babashka/issues/936#issuecomment-882105146)

**Comment by bobisageek** [comment]
Ahh yes, I see that using `identity` definitely doesn't work on Windows. I'll keep experimenting, and if I can make some progress, then maybe we can talk about if there's a fix that can handle at least both of these situations.
