### ISSUE TITLE
tagged-literal as the default when -I flag is used

### ISSUE THREAD

**Issue by justone** [babashka/babashka#975]
**Is your feature request related to a problem? Please describe.**
I was attempting to read an edn stream with unknown tagged literals using the `-I` facility, and `bb` was failing to parse the tagged literals. For instance:

```
❯ echo '{:foo #some-tag "bar"}' | bb -I -O '(map :foo *input*)'
----- Error --------------------------------------------------------------------
Type:     clojure.lang.EdnReader$ReaderException
Message:  java.lang.RuntimeException: No reader function for tag some-tag
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (map :foo *input*)
   ^--- java.lang.RuntimeException: No reader function for tag some-tag

----- Stack trace --------------------------------------------------------------
clojure.core/map - <built-in>
user             - <expr>:1:1
```

I attempted to use `set!` to set `*data-readers*`, but that didn't work:
```
❯ echo '{:foo #some-tag "bar"}' | bb -I -O '(set! *data-readers* {:default tagged-literal})(map :foo *input*)'
----- Error --------------------------------------------------------------------
Type:     clojure.lang.EdnReader$ReaderException
Message:  java.lang.RuntimeException: No reader function for tag some-tag
Location: <expr>:1:48

----- Context ------------------------------------------------------------------
1: (set! *data-readers* {:default tagged-literal})(map :foo *input*)
                                                  ^--- java.lang.RuntimeException: No reader function for tag some-tag

----- Stack trace --------------------------------------------------------------
clojure.core/map - <built-in>
user             - <expr>:1:48
```

**Describe the solution you'd like**
It would be useful to have `*input*` use `*data-readers*` and if the default would be `tagged-literal`.

**Describe alternatives you've considered**
I could take on reading edn forms myself, but it would be really nice if bb supported this out of the box.

**Additional context**
N/A

**Comment by bobisageek** [comment]
If my poking around is correct, then there are currently 3 spots where we try to read EDN into `*input*`:

`-I` without `--stream` ultimately calls `edn-seq*`:
https://github.com/babashka/babashka/blob/a85d593767fc9d1986442f3a248904a6623c7b50/src/babashka/main.clj#L425-L427 

`--stream` without `-i` sort of implies `-I`, because it tries to read the first EDN form:
https://github.com/babashka/babashka/blob/a85d593767fc9d1986442f3a248904a6623c7b50/src/babashka/main.clj#L676-L679

and if none of `#{ -I -i --stream}` are provided, then bb reads exactly the first EDN form from stdin:
https://github.com/babashka/babashka/blob/a85d593767fc9d1986442f3a248904a6623c7b50/src/babashka/main.clj#L684-L685

The original statement covers `-I`, which in my mind includes the first two, but I'm wondering if it makes sense to also do the third, so that behavior is consistent in the sense that "if we try to read EDN into `*input*`, `tagged-literal` is the `:default`"?

I have some further questions around using `*data-readers*`, and I'm also happy to let @justone take this one if they'd prefer, but I'm happy to contribute.

**Comment by justone** [comment]
Go for it, @bobisageek. Thank you.

**Comment by borkdude** [comment]
@bobisageek I think you're right: the third case should also be included: just any case in which `*input*` is used for EDN reading.

Btw, it occurred to me that `*data-readers*` doesn't affect `clojure.edn/read-string` in Clojure JVM either, so it probably shouldn't in bb either, so let's leave it at that. People can always use `edn/read-string` + `*in*` instead of `*input*` if they want more customized behavior.

**Comment by bobisageek** [comment]
Ok, #976 is in for using `tagged-literal`.

Just a thought about `*data-readers*`, mostly unrelated to `*input*` as such. I haven't thought this all the way through, so please pick holes in my logic. I also haven't really thought through the implementation, so what I'm thinking might be anywhere between trivial and impossible to actually do.

When we populate `*input*`, we use a one-off `:reader` map:
https://github.com/babashka/babashka/blob/a85d593767fc9d1986442f3a248904a6623c7b50/src/babashka/main.clj#L421-L423

This reader doesn't make it into the sci context, which can lead to some 'asymmetric' behavior (this behavior is unaffected by #976 ):
```clj
; ordered maps work when they're from stdin
$ echo '#ordered/map([:a 1])' | bb "(:a *input*)"
1

; but not in an expression (or at the REPL)
$ bb "(:a #ordered/map([:a 1]))"
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  No reader function for tag ordered/map
```

What I'd like to request feedback on (and maybe we even want to take this to a separate issue??) is the idea of adding these reader(s) into babashka's sci context.

**Comment by borkdude** [comment]
That's what I referred to with this:

> Btw, it occurred to me that *data-readers* doesn't affect clojure.edn/read-string in Clojure JVM either

They are two different configurations in Clojure JVM as well, so let's not conflate them in bb either I would say.

**Comment by borkdude** [comment]
Thanks for solving this issue @bobisageek !
